// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232.LMS.BusinessObjects;

public partial class Grade
{
    public int GradeId { get; set; }

    public int EnrollmentId { get; set; }

    public int SubjectId { get; set; }

    public decimal? MidtermScore { get; set; }

    public decimal? FinalScore { get; set; }

    public decimal? TotalScore { get; set; }

    public string LetterGrade { get; set; }

    public virtual Enrollment Enrollment { get; set; }

    public virtual Subject Subject { get; set; }
}