// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232.LMS.BusinessObjects;

public partial class Student
{
    public int StudentId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public DateTime DateOfBirth { get; set; }

    public virtual ICollection<Enrollment> Enrollments { get; set; } = new List<Enrollment>();
}