// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232.LMS.BusinessObjects;

public partial class Subject
{
    public int SubjectId { get; set; }

    public string SubjectCode { get; set; }

    public string SubjectName { get; set; }

    public int Credit { get; set; }

    public virtual ICollection<CourseSubject> CourseSubjects { get; set; } = new List<CourseSubject>();

    public virtual ICollection<Grade> Grades { get; set; } = new List<Grade>();
}