// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232.LMS.Repositories.Models;

public partial class CourseSubject
{
    public int CourseSubjectId { get; set; }

    public int CourseId { get; set; }

    public int SubjectId { get; set; }

    public virtual Course Course { get; set; }

    public virtual Subject Subject { get; set; }
}