// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232.LMS.Repositories.Models;

public partial class Semester
{
    public int SemesterId { get; set; }

    public string SemesterName { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}