// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRN232.LMS.Repositories;

#nullable disable

namespace PRN232.LMS.Repositories.Migrations
{
    [DbContext(typeof(LMSDatabaseContext))]
    [Migration("20260606075249_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRN232.LMS.Repositories.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex(new[] { "SemesterId" }, "IX_Course_Semester");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Models.CourseSubject", b =>
                {
                    b.Property<int>("CourseSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseSubjectId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("CourseSubjectId");

                    b.HasIndex("SubjectId");

                    b.HasIndex(new[] { "CourseId", "SubjectId" }, "UQ_CourseSubject")
                        .IsUnique();

                    b.ToTable("CourseSubject", (string)null);
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex(new[] { "CourseId" }, "IX_Enrollment_Course");

                    b.HasIndex(new[] { "Status" }, "IX_Enrollment_Status");

                    b.HasIndex(new[] { "StudentId" }, "IX_Enrollment_Student");

                    b.HasIndex(new[] { "StudentId", "CourseId" }, "UQ_Enrollment")
                        .IsUnique();

                    b.ToTable("Enrollment", (string)null);
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<decimal?>("FinalScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("LetterGrade")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<decimal?>("MidtermScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("GradeId");

                    b.HasIndex("SubjectId");

                    b.HasIndex(new[] { "EnrollmentId" }, "IX_Grade_Enrollment");

                    b.HasIndex(new[] { "EnrollmentId", "SubjectId" }, "UQ_Grade")
                        .IsUnique();

                    b.ToTable("Grade", (string)null);
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Models.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("SemesterId");

                    b.ToTable("Semester", (string)null);
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StudentId");

                    b.HasIndex(new[] { "Email" }, "IX_Student_Email");

                    b.HasIndex(new[] { "Email" }, "UQ_Student_Email")
                        .IsUnique();

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<int>("Credit")
                        .HasColumnType("int");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubjectId");

                    b.HasIndex(new[] { "SubjectCode" }, "UQ_Subject_Code")
                        .IsUnique();

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Models.Course", b =>
                {
                    b.HasOne("PRN232.LMS.Repositories.Models.Semester", "Semester")
                        .WithMany("Courses")
                        .HasForeignKey("SemesterId")
                        .IsRequired()
                        .HasConstraintName("FK_Course_Sem");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Models.CourseSubject", b =>
                {
                    b.HasOne("PRN232.LMS.Repositories.Models.Course", "Course")
                        .WithMany("CourseSubjects")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_CS_Course");

                    b.HasOne("PRN232.LMS.Repositories.Models.Subject", "Subject")
                        .WithMany("CourseSubjects")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_CS_Subject");

                    b.Navigation("Course");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Models.Enrollment", b =>
                {
                    b.HasOne("PRN232.LMS.Repositories.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_Enrollment_Course");

                    b.HasOne("PRN232.LMS.Repositories.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Enrollment_Student");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Models.Grade", b =>
                {
                    b.HasOne("PRN232.LMS.Repositories.Models.Enrollment", "Enrollment")
                        .WithMany("Grades")
                        .HasForeignKey("EnrollmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Grade_Enrollment");

                    b.HasOne("PRN232.LMS.Repositories.Models.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Grade_Subject");

                    b.Navigation("Enrollment");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Models.Course", b =>
                {
                    b.Navigation("CourseSubjects");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Models.Enrollment", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Models.Semester", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("PRN232.LMS.Repositories.Models.Subject", b =>
                {
                    b.Navigation("CourseSubjects");

                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
