@HostAddress = http://localhost:5288

# GET {{HostAddress}}/api/semesters
# Accept: application/json

# ###

# GET {{HostAddress}}/api/semesters/1
# Accept: application/json

# ###

# GET {{HostAddress}}/api/courses
# Accept: application/json

# ###

# GET {{HostAddress}}/api/courses/1
# Accept: application/json

# ###

# GET {{HostAddress}}/api/subjects
# Accept: application/json

# ###

# GET {{HostAddress}}/api/subjects/1
# Accept: application/json

###

GET {{HostAddress}}/api/students
Accept: application/json

###

GET {{HostAddress}}/api/students?search=nguyen
Accept: application/json

###

GET {{HostAddress}}/api/students?sort=fullName,-dateOfBirth
Accept: application/json

###

GET {{HostAddress}}/api/students?page=2&size=10
Accept: application/json

###

GET {{HostAddress}}/api/students?fields=studentId,fullName,email
Accept: application/json

###

GET {{HostAddress}}/api/students/1
Accept: application/json

###

GET {{HostAddress}}/api/enrollments
Accept: application/json

###

GET {{HostAddress}}/api/enrollments?expand=student,course
Accept: application/json

###

GET {{HostAddress}}/api/enrollments?search=active&sort=-enrollDate&page=1&size=20&fields=enrollmentId,status&expand=student,course
Accept: application/json

###

GET {{HostAddress}}/api/enrollments/10
Accept: application/json

